### ISSUE TITLE
Features TODO:

### ISSUE THREAD

**Issue by EternalCode** [EternalCode/Dark-Wish#1]
## Unrelated to battle
- [ ] Dive
- [ ] Ability Synchronize
- [x] Move animation core
- [ ] Move scripts
- [x] Capturing in battle engine
- [x] Experience gain in battle engine
- [ ] Icons
- [ ] Height tables
- [ ] Shiny sprites
- [ ] Evolution mechanics
- [ ] Forms
- [ ] Item abilities + Aegislash's ability
- [ ] Items
